[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
category = "Utility"
feature = false
app = false
title = "Embedded Jupyter Notebook"
description = "Jupyter Notebook version of Omniverse's script editor"
authors = ["Toni-SM"]
repository = "https://github.com/Toni-SM/semu.misc.jupyter_notebook"
keywords = ["jupyter", "notebook", "ipython", "editor"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[package.target]
config = ["release"]
platform = ["linux-*", "windows-*"]
python = ["*"]

[dependencies]
"omni.kit.test" = {}
"omni.kit.uiapp" = {}
"omni.kit.notification_manager" = {}

[[python.module]]
name = "semu.misc.jupyter_notebook"

[python.pipapi]
requirements = ["nest_asyncio", "jupyterlab", "notebook", "jedi"]
use_online_index = true

[settings]
# extension settings
exts."semu.misc.jupyter_notebook".socket_port = 8224
exts."semu.misc.jupyter_notebook".run_in_external_process = true
exts."semu.misc.jupyter_notebook".classic_notebook_interface = false
exts."semu.misc.jupyter_notebook".kill_processes_with_port_in_use = true
# jupyter notebook settings
exts."semu.misc.jupyter_notebook".notebook_ip = "0.0.0.0"
exts."semu.misc.jupyter_notebook".notebook_port = 8225
exts."semu.misc.jupyter_notebook".token = ""
exts."semu.misc.jupyter_notebook".notebook_dir = ""
# jupyter notebook's command line options other than: '--ip', '--port', '--token', '--notebook-dir'
exts."semu.misc.jupyter_notebook".command_line_options = "--allow-root --no-browser --JupyterApp.answer_yes=True"
